export default {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  ERROR_GENERIC: 'ERROR_GENERIC',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  LOAD_PACKCARDS: 'LOAD_PACKCARDS',
  GETRANDOM_PACKCARD: 'GETRANDOM_PACKCARD',
  ADD_SUBSCRIPTOR_PACKCARD: 'ADD_SUBSCRIPTOR_PACKCARD'

};
