export default {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  ERROR_GENERIC: 'ERROR_GENERIC',
  LOAD_PACKARDS: 'LOAD_PACKARDS',
  GETRANDOM_PACKCARD: 'GETRANDOM_PACKCARD'

};
